[theme]
primaryColor = "#5b53c7"
backgroundColor = "#0E1117"  
secondaryBackgroundColor = "#262730"  
textColor = "#FAFAFA" 
font = "sans serif"
widgetBackgroundColor = "#262730"
borderColor = "#4F5B66"
